[package]
name = "ubpp"
version = "0.1.0"
edition = "2021"

[lib]
name = "ubpplib"
crate-type = ["rlib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pest = "2.3.1"
pest_derive = "2.3.1"
